### PR TITLE
Throw error of try/catch instead of a Error() when set state

### PR DESCRIPTION
**Pull request by tbm98**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

What is the use-case? I'm all for changing `Error` to something more specific. But I don't think throwing the original exception is a good call (on top of that, there can be more than one)

That would mean the exception thrown by `state =` would changed based on the number of listeners and what they do. I don't like the idea of coupling those logics.

**Comment by tbm98** [comment]
I think throw original exceptions is helpful to trace/ identify problems more quickly. Currently, it only throws Error() without information and developers don't know why it happens.

**Comment by tbm98** [comment]
instance is this error: [river_pod/issues/730](https://github.com/rrousselGit/river_pod/issues/730)

it only show 
```
======== Exception caught by gesture ===============================================================
The following Error was thrown while handling a gesture:
Instance of 'Error'
```

**Comment by tbm98** [comment]
Oh. I didn't know that can has multiple exception

**Pull request closed without merging**
